name: Create files for GitHub Release


env:
    project_url: 'https://github.com/${{ github.repository }}'
    latest_manifest_url: 'https://github.com/${{ github.repository }}/releases/latest/download/module.json'
    release_url: 'https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/module.zip'


on:
    push:
        tags:
            - '*'


jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: yarn install
                run: yarn install

            -   name: Pack compendiums
                run: yarn run pack-packs

            -   name: Modify manifest with release-specific values
                id: sub_manifest_link_version
                uses: cschleiden/replace-tokens@v1
                with:
                    files: 'module.json'
                env:
                    VERSION: ${{ github.ref_name }}
                    URL: ${{ env.project_url }}
                    MANIFEST: ${{ env.latest_manifest_url }}
                    DOWNLOAD: ${{ env.release_url }}

            -   name: Create archive
                run: |
                    zip                                    \
                      --recurse-paths                      \
                       ./module.zip                        \
                      module.json                          \
                      README.md                            \
                      CHANGELOG.md                         \
                      LICENSE                              \
                      scripts/                             \
                      packs/                               \
                      assets/
